/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ru.belov.blackjack;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import ru.belov.blackjack.players.Player;

/**
 *
 * @author Xiaomi
 */
public abstract class PlayersScreen extends javax.swing.JFrame implements UpdateVisualInfo {

    protected MyWindowAdapter adapter = new MyWindowAdapter();
    protected final StartScreen parent;
    protected Game game = new Game();
    protected int winnings = 0;
    protected int losses = 0;
    protected Map<Player, JLabel> map = new HashMap<>();

    public void checkOn21and22() {
        for (int i = 0; i < game.getPlayers().size(); i++) {
            Player player = game.getPlayers().get(i);
            if (player.getTotalPoints() == 21 || player.getTotalPoints() == 22) {
                MyWindowAdapter adapter = new MyWindowAdapter();
                if (i == 0) {
                    adapter.initWinClosing(this, parent, "вы сходу выиграли эту игру! \nНачать новую или выйти в меню?");
                } else {
                    adapter.initLoseClosing(this, parent, "вы сходу  проиграли игру, так как игрок " + player.getName() + " набрал " + player.getTotalPoints() + " очка!\nНачать новую или выйти в меню?");
                }
            }
        }
    }

    public PlayersScreen(StartScreen parent) {
        this.parent = parent;
        initComponents();
        this.addWindowListener(new MyWindowAdapter());
    }

    public Game getGame() {
        return game;
    }

    public Map<Player, JLabel> getMap() {
        return map;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    public int getWinnings() {
        return winnings;
    }

    public void setWinnings(int winnings) {
        this.winnings = winnings;
    }

    public int getLosses() {
        return losses;
    }

    public void setLosses(int losses) {
        this.losses = losses;
    }

    @Override
    public StartScreen getParent() {
        return parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    abstract void startGame();

    abstract JLabel getBankInfoLabel();

    abstract JLabel getLossesLabel();

    abstract JLabel getWinningsLabel();

    abstract JLabel getLastMoveInfo();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
