package ru.belov.blackjack;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Xiaomi
 */
public class StartScreen extends javax.swing.JFrame {

    private int globalWinnings = 0;
    private int globalLosses = 0;
    private int globalBank = 100;
    private List<JComboBox<String>> comboBoxs;
    private Map<JComboBox<String>, String> chosenNuclides;

    public void setGlobalWinnings(int globalWinnings) {
        this.globalWinnings = globalWinnings;
    }

    public void setGlobalLosses(int globalLosses) {
        this.globalLosses = globalLosses;
    }

    public int getGlobalWinnings() {
        return globalWinnings;
    }

    public int getGlobalLosses() {
        return globalLosses;
    }

    public int getGlobalBank() {
        return globalBank;
    }

    public void setGlobalBank(int globalBank) {
        this.globalBank = globalBank;
    }

    public JLabel getGlobalLossesLabel() {
        return globalLossesLabel;
    }

    public JLabel getGlobalWinningsLabel() {
        return globalWinningsLabel;
    }

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
        ImageIcon img = new ImageIcon(System.getProperty("user.dir") + "/imgSource/atom.png");
        ImageIcon img2 = new ImageIcon(System.getProperty("user.dir") + "/imgSource/startScreenCards.png");
        ImageIcon resizedImg = new ImageIcon(img.getImage().getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH));
        ImageIcon resizedImg2 = new ImageIcon(img2.getImage().getScaledInstance(250, 150, java.awt.Image.SCALE_SMOOTH));
        nameOfGame.setIcon(resizedImg);
        picture.setIcon(resizedImg2);
        updateStatistics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setCrads = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        nameLable = new javax.swing.JLabel();
        nuclideLable = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        sixLable = new javax.swing.JLabel();
        sevenLable = new javax.swing.JLabel();
        eightLable = new javax.swing.JLabel();
        nineLable = new javax.swing.JLabel();
        tenLable = new javax.swing.JLabel();
        jackLable = new javax.swing.JLabel();
        queenLable = new javax.swing.JLabel();
        kingLable = new javax.swing.JLabel();
        aceLable = new javax.swing.JLabel();
        sixComboBox = new javax.swing.JComboBox<>();
        sevenComboBox = new javax.swing.JComboBox<>();
        eightComboBox = new javax.swing.JComboBox<>();
        nineComboBox = new javax.swing.JComboBox<>();
        tenComboBox = new javax.swing.JComboBox<>();
        jackComboBox = new javax.swing.JComboBox<>();
        queenComboBox = new javax.swing.JComboBox<>();
        kingComboBox = new javax.swing.JComboBox<>();
        aceComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        nameOfGame = new javax.swing.JLabel();
        setCardsButton = new javax.swing.JButton();
        startGameButton = new javax.swing.JButton();
        picture = new javax.swing.JLabel();
        playersLabel = new javax.swing.JLabel();
        playersComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        globalWinningsLabel = new javax.swing.JLabel();
        globalLossesLabel = new javax.swing.JLabel();
        globalBankLabel = new javax.swing.JLabel();

        setCrads.setFocusTraversalPolicyProvider(true);
        setCrads.setSize(new java.awt.Dimension(440, 400));

        nameLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLable.setText("Достоинство");

        nuclideLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nuclideLable.setText("Нуклид");

        saveButton.setText("Сохранить");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        sixLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        sixLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sixLable.setText("6");

        sevenLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        sevenLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sevenLable.setText("7");

        eightLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        eightLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eightLable.setText("8");

        nineLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        nineLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nineLable.setText("9");

        tenLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        tenLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenLable.setText("10");

        jackLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jackLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jackLable.setText("Jack");

        queenLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        queenLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queenLable.setText("Queen");

        kingLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        kingLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kingLable.setText("King");

        aceLable.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        aceLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aceLable.setText("Ace");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sixLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nineLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eightLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sevenLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jackLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(queenLable, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(kingLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aceLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sixComboBox, 0, 152, Short.MAX_VALUE)
                    .addComponent(sevenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eightComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nineComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jackComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(queenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kingComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixLable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenLable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sevenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eightLable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nineLable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jackLable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jackComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queenLable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kingLable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceLable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuclideLable, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLable)
                    .addComponent(nuclideLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout setCradsLayout = new javax.swing.GroupLayout(setCrads.getContentPane());
        setCrads.getContentPane().setLayout(setCradsLayout);
        setCradsLayout.setHorizontalGroup(
            setCradsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setCradsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        setCradsLayout.setVerticalGroup(
            setCradsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setCradsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        nameOfGame.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        nameOfGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameOfGame.setText("Nuclear black jack");

        setCardsButton.setText("Редактировать колоду");
        setCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCardsButtonActionPerformed(evt);
            }
        });

        startGameButton.setText("Начать игру");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playersLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playersLabel.setText("выберите число соперников:");

        playersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel1.setText("Глобальный счет:");

        globalWinningsLabel.setText("Победы:");

        globalLossesLabel.setText("Поражения:");

        globalBankLabel.setText("Банк:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(setCardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playersLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(playersComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nameOfGame, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(globalLossesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(globalWinningsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(globalBankLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameOfGame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setCardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playersLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(globalWinningsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(globalLossesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(globalBankLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCardsButtonActionPerformed
        initComboBoxes();
        setCrads.setVisible(true);
    }//GEN-LAST:event_setCardsButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        refreshCards();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        switch (Integer.parseInt((String) playersComboBox.getSelectedItem())) {
            case 1 -> {
                PlayersScreen screen = new TwoPlayersScreen(this);
                int x = (screenSize.width - screen.getWidth()) / 2;
                int y = (screenSize.height - screen.getHeight()) / 2;
                screen.setLocation(x, y);
                screen.setVisible(true);
            }
            case 2 -> {
                PlayersScreen screen = new ThreePlayersScreen(this);
                int x = (screenSize.width - screen.getWidth()) / 2;
                int y = (screenSize.height - screen.getHeight()) / 2;
                screen.setLocation(x, y);
                screen.setVisible(true);
            }
            case 3 -> {
                PlayersScreen screen = new FourPlayersScreen(this);
                int x = (screenSize.width - screen.getWidth()) / 2;
                int y = (screenSize.height - screen.getHeight()) / 2;
                screen.setLocation(x, y);
                screen.setVisible(true);
            }
            case 4 -> {
                PlayersScreen screen = new FivePlayersScreen(this);
                int x = (screenSize.width - screen.getWidth()) / 2;
                int y = (screenSize.height - screen.getHeight()) / 2;
                screen.setLocation(x, y);
                screen.setVisible(true);
            }
            default ->
                throw new AssertionError();
        }
    }//GEN-LAST:event_startGameButtonActionPerformed



    public int getBalanceForGame() {
//        System.out.println("банк перед началом игры до взятия денег: " + globalBank);
        if (globalBank >= 100) {
            globalBank -= 100;
//            System.out.println("банк после взятия денег и начала: " + globalBank);
            return 100;
        } else {
            int balanceForGame = globalBank;
            globalBank = 0;
//            System.out.println("банк после взятия денег и начала: " + globalBank);
            return balanceForGame;
        }
    }

    private void initComboBoxes() {
        chosenNuclides = new HashMap<>();
        comboBoxs = new ArrayList<>();
        comboBoxs.add(sixComboBox);
        comboBoxs.add(sevenComboBox);
        comboBoxs.add(eightComboBox);
        comboBoxs.add(nineComboBox);
        comboBoxs.add(tenComboBox);
        comboBoxs.add(jackComboBox);
        comboBoxs.add(queenComboBox);
        comboBoxs.add(kingComboBox);
        comboBoxs.add(aceComboBox);
        var cards = Card.values();
        var nuclides = Nuclide.values();
        for (Nuclide nuclide : nuclides) {
            comboBoxs.stream().forEach(box -> box.addItem(nuclide.getName()));
        }
        for (int i = 0; i < cards.length; i++) {
            comboBoxs.get(i).setSelectedItem(cards[i].getNuclide().getName());
            comboBoxs.stream().forEach(box -> chosenNuclides.put(box, (String) box.getSelectedItem()));
            for (int j = 0; j < comboBoxs.size(); j++) {
                if (i != j) {
                    DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) comboBoxs.get(j).getModel();
                    model.removeElement(comboBoxs.get(i).getSelectedItem());
                }
            }
        }

        comboBoxs.stream().forEach(box -> box.addItemListener(this::itemStateChanged));
    }

    private void itemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
            JComboBox comboBox = (JComboBox) e.getSource();
            String oldValue = chosenNuclides.get(comboBox);
            comboBoxs.stream().forEach(box -> {
                if (!comboBox.equals(box)) {
                    DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) box.getModel();
                    model.removeElement(comboBox.getSelectedItem());
                    model.addElement(oldValue);
                }
            });
            chosenNuclides.put(comboBox, (String) comboBox.getSelectedItem());
        }
    }

    private void refreshCards() {
        var nuclides = Nuclide.values();
        Map<String, Nuclide> nucMap = new HashMap<>();
        for (Nuclide nuclide : nuclides) {
            nucMap.put(nuclide.getName(), nuclide);
        }
        Card.SIX.setNuclide(nucMap.get(chosenNuclides.get(sixComboBox)));
        Card.SEVEN.setNuclide(nucMap.get(chosenNuclides.get(sevenComboBox)));
        Card.EIGHT.setNuclide(nucMap.get(chosenNuclides.get(eightComboBox)));
        Card.NINE.setNuclide(nucMap.get(chosenNuclides.get(nineComboBox)));
        Card.TEN.setNuclide(nucMap.get(chosenNuclides.get(tenComboBox)));
        Card.JACK.setNuclide(nucMap.get(chosenNuclides.get(jackComboBox)));
        Card.QUEEN.setNuclide(nucMap.get(chosenNuclides.get(queenComboBox)));
        Card.KING.setNuclide(nucMap.get(chosenNuclides.get(kingComboBox)));
        Card.ACE.setNuclide(nucMap.get(chosenNuclides.get(aceComboBox)));
        setCrads.dispose();
    }

    public void updateStatistics() {
        globalLossesLabel.setText("проигрыши: " + globalLosses);
        globalWinningsLabel.setText("выигрыши: " + globalWinnings);
        globalBankLabel.setText("Банк: " + globalBank);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aceComboBox;
    private javax.swing.JLabel aceLable;
    private javax.swing.JComboBox<String> eightComboBox;
    private javax.swing.JLabel eightLable;
    private javax.swing.JLabel globalBankLabel;
    private javax.swing.JLabel globalLossesLabel;
    private javax.swing.JLabel globalWinningsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jackComboBox;
    private javax.swing.JLabel jackLable;
    private javax.swing.JComboBox<String> kingComboBox;
    private javax.swing.JLabel kingLable;
    private javax.swing.JLabel nameLable;
    private javax.swing.JLabel nameOfGame;
    private javax.swing.JComboBox<String> nineComboBox;
    private javax.swing.JLabel nineLable;
    private javax.swing.JLabel nuclideLable;
    private javax.swing.JLabel picture;
    private javax.swing.JComboBox<String> playersComboBox;
    private javax.swing.JLabel playersLabel;
    private javax.swing.JComboBox<String> queenComboBox;
    private javax.swing.JLabel queenLable;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton setCardsButton;
    private javax.swing.JFrame setCrads;
    private javax.swing.JComboBox<String> sevenComboBox;
    private javax.swing.JLabel sevenLable;
    private javax.swing.JComboBox<String> sixComboBox;
    private javax.swing.JLabel sixLable;
    private javax.swing.JButton startGameButton;
    private javax.swing.JComboBox<String> tenComboBox;
    private javax.swing.JLabel tenLable;
    // End of variables declaration//GEN-END:variables
}
